# Generated by Django 5.1.6 on 2025-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Max_Temperature', models.FloatField(blank=True, null=True)),
                ('Min_Temperature', models.FloatField(blank=True, null=True)),
                ('Humidity', models.IntegerField(blank=True, null=True)),
                ('Max_Humidity', models.IntegerField(blank=True, null=True)),
                ('Min_humidity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
