# Generated by Django 5.1.6 on 2025-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
