# Generated by Django 5.1.6 on 2025-03-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_weatherrecord_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='Humidity',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='Max_Humidity',
            new_name='max_Humidity',
        ),
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='Max_Temperature',
            new_name='max_Temperature',
        ),
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='Min_Temperature',
            new_name='min_Temperature',
        ),
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='Min_humidity',
            new_name='min_humidity',
        ),
    ]
